### ISSUE TITLE
support for infinite section scrolling

### ISSUE THREAD

**Issue by satishVekariya** [joelekstrom/JEKScrollableSectionCollectionViewLayout#10]
I think infinite section scrolling is grate feature.
**What do you mean infinite scrolling:**
1. first cell reappear at end of section
2. infinite scrolling is only enable for scrollable content and `isInfiniteScrollable = true` and it support both direction

**Comment by joelekstrom** [comment]
Hi! Thanks for the suggestion.

I believe this is out of scope for this project as it will complicate the code base for a feature I believe will rarely be used.

It sounds like a good candidate for a subclass of this layout though, and I’d love to see a fork/subproject that supports it!
