### ISSUE TITLE
Can this do paging?

### ISSUE THREAD

**Issue by henrydeclety** [joelekstrom/JEKScrollableSectionCollectionViewLayout#11]
I set 
`collectionView.isPagingEnabled = true `
but it doesn't seem to work.

**Comment by joelekstrom** [comment]
Hi!

Yes, it can, you need to use the scroll view configuration. Either you enable it for all section when creating the layout:
```swift
layout.defaultScrollViewConfiguration.pagingEnabled = true
```

Or you implement `collectionView:layout:scrollViewConfigurationForSection:section` and you can enable it for specific sections only.

Let me know if it doesn't work!

**Comment by henrydeclety** [comment]
Okay awesome! How would you go about redefining the page size though? Because it doesn't exactly scroll to the offset I would want it to.

**Comment by joelekstrom** [comment]
You can do it in `scrollViewWillEndDragging`, but there's a specific one that works per section if you conform to `JEKCollectionViewDelegateScrollableSectionLayout`:

`- (void)collectionView:(UICollectionView *)collectionView layout:(JEKScrollableSectionCollectionViewLayout *)layout sectionWillEndDragging:(NSUInteger)section withVelocity:(CGFloat)velocity targetOffset:(inout CGFloat *)targetHorizontalOffset;`

**Comment by henrydeclety** [comment]
Awesome, many thanks!

**Comment by joelekstrom** [comment]
I hope it will work fine!
