### ISSUE TITLE
Crash when accessing `indexPath.section`

### ISSUE THREAD

**Issue by MaxHasADHD** [joelekstrom/JEKScrollableSectionCollectionViewLayout#13]
Hi there, I am using this layout in a Swift project, and when accessing the `section` property of the `indexPath` passed in through `viewForSupplementaryElementOfKind` and other `UICollectionViewDataSource` methods the app will crash on the getter

**Comment by joelekstrom** [comment]
Hi! Thanks for the report.

Are you sure that the `section`-property is what's crashing? The index paths for supplementary items only contain a single index (so for example, `indexPath.item` or `indexPath.row`) is expected to crash. But I'm quite certain that the `section` getter of `NSIndexPath` is equivalent to calling `index(atPosition: 0)`. Could you verify by trying to access position 0 instead?

If the `section` property is really crashing, I'd love if you could paste the stack trace here!

**Comment by ktxc15** [comment]
I have the same problem
Here is simple example it crash as question, could you please take a look and give advise @joelekstrom , @MaxHasADHD 
https://drive.google.com/file/d/1Y5276jbZoHLOt7WCKjiBOnvUDAfI4gNc/view?usp=sharing

**Comment by joelekstrom** [comment]
@ktxc15 Thanks for the example project!

This actually seems to be some weirdness with Swifts `IndexPath`-class. I'll take a look at what the reason could be, but for now you can use `(indexPath as NSIndexPath).section` and it will work 🤔

**Comment by ktxc15** [comment]
Thank @joelekstrom , it work now

**Comment by joelekstrom** [comment]
New version out on CocoaPods with a fix that is compatible with Swift `IndexPath`
