### ISSUE TITLE
Horizontal scroll for particular section

### ISSUE THREAD

**Issue by RohithPsingh** [joelekstrom/JEKScrollableSectionCollectionViewLayout#21]
Hi
 i have 9 sections totally, need to scroll horizontal for 3 sections. 
in the below delegate method i added  these two lines., but still it doesn't work
 
 collectionView.isPagingEnabled = true
 layout.defaultScrollViewConfiguration.isPagingEnabled = true
 
func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize

If i add the below code in viewDidLoad its reflecting to all sections. 
  
  let layout = JEKScrollableSectionCollectionViewLayout()
  dashBoardCollectionView.collectionViewLayout = layout

can you please help me out from this., please share some sample code(swift) in detail with these possibilities.. 

Thanks

**Comment by joelekstrom** [comment]
Hi!

To achieve this, your controller class should conform to `JEKCollectionViewDelegateScrollableSectionLayout`, and then implement the following method. This example disables scrolling for section 2:

```swift
func collectionView(_ collectionView: UICollectionView, layout: JEKScrollableSectionCollectionViewLayout, scrollViewConfigurationForSection section: UInt) -> JEKScrollViewConfiguration? {
    let config = JEKScrollViewConfiguration.default()
    if section == 2 {
        config.isScrollEnabled = false
    }
    return config;
}
```

You can customize each section in several ways using this method.

**Comment by RohithPsingh** [comment]
> Hi!
> 
> To achieve this, your controller class should conform to `JEKCollectionViewDelegateScrollableSectionLayout`, and then implement the following method. This example disables scrolling for section 2:
> 
> ```swift
> func collectionView(_ collectionView: UICollectionView, layout: JEKScrollableSectionCollectionViewLayout, scrollViewConfigurationForSection section: UInt) -> JEKScrollViewConfiguration? {
>     let config = JEKScrollViewConfiguration.default()
>     if section == 2 {
>         config.isScrollEnabled = false
>     }
>     return config;
> }
> ```
> 
> You can customize each section in several ways using this method.

Thanks much.,its working fine..
i have one more query. i have few sections need to display full array count in vertical. like i have 8 cells in one section need to show in vertical, but here its showing in horizontal with 3 cells in screen without scroll. 
which delegate method we need to use . please help..

**Comment by joelekstrom** [comment]
Ah, I think you want to use a flow layout in those sections. Try this method instead:

```swift
func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: JEKScrollableSectionCollectionViewLayout, shouldUseFlowLayoutInSection section: Int) -> Bool {
    if section == 2 {
        return true
    }
    return false
}
```

This way, the whole section should layout like a standard flow layout, meaning that if there are more cells than fit horizontally it will add several rows instead.

**Comment by RohithPsingh** [comment]
> Right in the bottom of the file `Tests.swift` there's an example of this delegate method in Swift.
> 
> The signature is `func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: JEKScrollableSectionCollectionViewLayout, shouldUseFlowLayoutInSection section: Int) -> Bool {`
> 
> If that's never called in your delegate, I think I need to see your whole controller class to find the error. Make sure you implemented it in the object set as `collectionView.delegate`.

i tried with all the possibilities., still i didnt get the right solution.., shouldUseFlowLayoutInSection delegate method is never called.
scrollViewConfigurationForSection this delegate method is calling. 

is the below lines mandatory to call., i wrote this two lines in viewDidLoad()
 let layout = JEKScrollableSectionCollectionViewLayout()
 dashBoardCollectionView.collectionViewLayout = layout

pls let me know if i need to correct anywhere..

Thanks

**Comment by RohithPsingh** [comment]
> Right in the bottom of the file `Tests.swift` there's an example of this delegate method in Swift.
> 
> The signature is `func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: JEKScrollableSectionCollectionViewLayout, shouldUseFlowLayoutInSection section: Int) -> Bool {`
> 
> If that's never called in your delegate, I think I need to see your whole controller class to find the error. Make sure you implemented it in the object set as `collectionView.delegate`.

delegate and datasource is configured through sotryboard., how to implement this below line :
"Make sure you implemented it in the object set as collectionView.delegate."

Thanks

**Comment by joelekstrom** [comment]
That should be OK. And since the other delegate method is called, I think it's wired up correctly. Very strange that this one ins't. Feels like it might be a typo or spelled incorrectly or something then? Anyway, it's hard for me to help unless you could post your whole controller class

**Comment by RohithPsingh** [comment]
> That should be OK. And since the other delegate method is called, I think it's wired up correctly. Very strange that this one isn’t called. Feels like it might be spelled incorrectly or something then? Since the tests pass (and example project works) the library itself should be doing the correct thing. Anyway, it's hard for me to help unless you could post your whole controller class

how to share class file to u., can u provide any email or any other way.?

**Comment by joelekstrom** [comment]
Send it to jek@ekstrom.io

**Comment by RohithPsingh** [comment]
Thanks much bro., issue resolved..
