### ISSUE TITLE
class is not key value coding-compliant for the key estimatedItemSize

### ISSUE THREAD

**Issue by PascalHarris** [joelekstrom/JEKScrollableSectionCollectionViewLayout#23]
I think that this might be the answer to my prayers - except that I get the error `[<JEKScrollableSectionCollectionViewLayout 0x101d096f0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key estimatedItemSize` when I try to use this code in my own project.

(There is one key difference with my project - I hope isn't the source of the problem.  My cell prototypes are in separate nib files rather than in the main nib. -- **experimentation indicates this isn't the problem**)

Also, when I tried to set the layout object in the main nib to be of type JEKScrollableSectionCollectionViewLayout it didn't autocomplete for me (which I expected it to).  I don't know if this is indicative of a problem.

`estimatedItemSize` appears to be part of uicollectionviewflowlayout (https://developer.apple.com/documentation/uikit/uicollectionviewflowlayout?language=objc), but I don't specifically access this in my code any more than you do in yours.  Besides, inserting break points, it doesn't seem to be getting as far as my code - it bombs out immediately, I suspect an issue with the nib (see point in para 3).

Clutching at straws - but could this to be something to do with the Tab bar that this view is accessed via?

Finally, thank you for your work on this, and for your elegant code.

**Comment by PascalHarris** [comment]
I solved the problem by adding `@property (nonatomic) CGSize estimatedItemSize;` to JEKScrollableSectionCollectionViewLayout.h - but that doesn't feel like the best solution.

**Comment by joelekstrom** [comment]
Sorry for my slow response and thanks for looking into this! I gather this is specifically a problem with nibs which may be why it hasn't shown up before.

Also, I don't really maintain this project anymore since Apple released `UICollectionViewCompositionalLayout` which should achieve the same. But I'm glad if it's still useful to you!
