### ISSUE TITLE
Determine a particular section

### ISSUE THREAD

**Issue by njawahire** [joelekstrom/JEKScrollableSectionCollectionViewLayout#5]
Hi,
Can we determine which section we are scrolling??
We have a scenario when we scroll a particular section we want to change background image. Any ideas on how we can achieve it?

Regards,
Nakash Jawahire

**Comment by accatyyc** [comment]
Hi! Without any changes to the library, could this be achieved by checking what cells are being shown by implementing `- (void)collectionView:(UICollectionView *)collectionView willDisplayCell:(UICollectionViewCell *)cell forItemAtIndexPath:(NSIndexPath *)indexPath;` and keeping track of that?

**Comment by njawahire** [comment]
actually we tried this
- (void)collectionView:(UICollectionView *)collectionView willDisplayCell:(UICollectionViewCell *)cell forItemAtIndexPath:(NSIndexPath *)indexPath;
but are not able to get the desired result...

**Comment by accatyyc** [comment]
Right, it requires some logic to get right. Let me think about this for a while and get back to you. It's probably possible to solve this via through key-value observing

**Comment by accatyyc** [comment]
Hey again. I couldn't find a clean version with KVO so I added a delegate protocol instead. Please try it out and see if it solves your problem by pointing your podfile to master and running `pod install`:

```
pod 'JEKScrollableSectionCollectionViewLayout, :git => 'https://github.com/accatyyc/JEKScrollableSectionCollectionViewLayout.git', :branch => 'master'
```

Then, in your view controller, instead of conforming to `UICollectionViewDelegateFlowLayout`, just replace that with `JEKCollectionViewDelegateScrollableSectionLayout`, and implement:

```objc
- (void)collectionView:(UICollectionView *)collectionView layout:(JEKScrollableSectionCollectionViewLayout *)layout sectionWillBeginDragging:(NSUInteger)section {
    // handle background change
}
```

Let me know if that solves your problem!

**Comment by njawahire** [comment]
Hi,
I did solved my problem but by using
`func collectionView(_ collectionView: UICollectionView!, layout: JEKScrollableSectionCollectionViewLayout!, section: UInt, didScrollToOffset horizontalOffset: CGFloat)`
not
`- (void)collectionView:(UICollectionView *)collectionView layout:(JEKScrollableSectionCollectionViewLayout *)layout sectionWillBeginDragging:(NSUInteger)section {
    // handle background change
}`

and I think you should add these delegates in readme too.

**Comment by accatyyc** [comment]
Yep, will add some docs together with the next release. Thanks for testing it
